version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"
      pip-version:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"
      actions-version:
        applies-to: version-updates
        patterns:
          - "*"
